version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - models_cache:/root/.cache 
      - ./assets:/app/assets:ro
      - ./models:/app/models
    expose:
      - "8000"  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 15s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  models_cache:
